#!/usr/bin/env python3
"""
png_to_h.py -- turn a 480x320 image into src/bg_image.h for j4_display_right.

  created:  2026-09-02 -KL
   author:  Kevin Lange

Emits plain RGB565 uint16_t words, which is the form a TFT_eSPI sprite holds
internally. Everything in main.cpp blits the background with swapBytes(false),
exactly as pushSprite() does, so this one format is correct both for pushes
straight to the panel and for copies into the bar band sprite. Do not "fix"
colours by changing setSwapBytes() in main.cpp; regenerate with --swap here.

Usage:
    ~/.platformio/penv/bin/python tools/png_to_h.py background.png
    ~/.platformio/penv/bin/python tools/png_to_h.py background.png --swap

The array lands in flash (about 300KB), not RAM.
"""

import sys
import os

try:
    from PIL import Image
except ImportError:
    sys.exit("Pillow is not installed. Try: ~/.platformio/penv/bin/pip install Pillow")

WIDTH  = 480
HEIGHT = 320

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                   "..", "src", "bg_image.h")


def to_rgb565(r, g, b):
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def main():
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    swap = "--swap" in sys.argv
    if len(args) != 1:
        sys.exit(__doc__)

    src = args[0]
    im = Image.open(src).convert("RGB")

    if im.size != (WIDTH, HEIGHT):
        print("resizing %dx%d -> %dx%d" % (im.size[0], im.size[1], WIDTH, HEIGHT))
        im = im.resize((WIDTH, HEIGHT), Image.LANCZOS)

    px = im.load()
    words = []
    for y in range(HEIGHT):
        for x in range(WIDTH):
            c = to_rgb565(*px[x, y])
            if swap:
                c = ((c & 0xFF) << 8) | (c >> 8)
            words.append(c)

    out = os.path.normpath(OUT)
    with open(out, "w") as f:
        f.write("// Generated by tools/png_to_h.py from %s\n" % os.path.basename(src))
        f.write("// Do not edit by hand. Regenerate instead.\n")
        f.write("//\n")
        f.write("// Plain RGB565 words, %d x %d, %d bytes in flash.\n"
                % (WIDTH, HEIGHT, WIDTH * HEIGHT * 2))
        f.write("// Blitted with swapBytes(false), matching how pushSprite() pushes.\n\n")
        f.write("#pragma once\n\n")
        f.write("#include <stdint.h>\n\n")
        f.write("#define BG_IMAGE_W  %d\n" % WIDTH)
        f.write("#define BG_IMAGE_H  %d\n\n" % HEIGHT)
        f.write("const uint16_t BG_IMAGE[%d] PROGMEM = {\n" % (WIDTH * HEIGHT))
        for i in range(0, len(words), 12):
            f.write("  " + ", ".join("0x%04X" % w for w in words[i:i + 12]) + ",\n")
        f.write("};\n")

    print("wrote %s (%d px, %d bytes of image data)"
          % (out, len(words), len(words) * 2))


if __name__ == "__main__":
    main()
