#!/usr/bin/env python3
"""
png_to_h.py -- turn a 480x320 image into src/bg_image.h for j4_display_right.

  created:  2026-09-02 -KL
   author:  Kevin Lange

Emits BYTE-SWAPPED RGB565 words by default, because that is what a TFT_eSPI
sprite holds internally: TFT_eSprite::drawPixel() stores
((color >> 8) | (color << 8)), and pushSprite() then sets swapBytes(false)
precisely because the buffer is already swapped. On top of that the ILI9488 is
a 3-byte RGB panel, so pushPixels() with swapBytes(false) writes through
tft_Write_16S(), which swaps its input again on the way out.

Both paths therefore want swapped words, and main.cpp blits everything with
swapBytes(false), so this default is correct for pushes straight to the panel
and for memcpy copies into the bar band sprite alike.

Getting this backwards does not produce a subtle tint. Smooth gradients break
into vivid blue, green and magenta banding while the geometry stays perfect,
because the high and low bytes of every pixel trade places.

Usage:
    ~/.platformio/penv/bin/python tools/png_to_h.py background.png
    ~/.platformio/penv/bin/python tools/png_to_h.py background.png --no-swap

The array lands in flash (about 300KB), not RAM.
"""

import sys
import os

try:
    from PIL import Image
except ImportError:
    sys.exit("Pillow is not installed. Try: ~/.platformio/penv/bin/pip install Pillow")

WIDTH  = 480
HEIGHT = 320

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                   "..", "src", "bg_image.h")


def to_rgb565(r, g, b):
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def main():
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    swap = "--no-swap" not in sys.argv   # swapped is the correct default here
    if len(args) != 1:
        sys.exit(__doc__)

    src = args[0]
    im = Image.open(src).convert("RGB")

    if im.size != (WIDTH, HEIGHT):
        print("resizing %dx%d -> %dx%d" % (im.size[0], im.size[1], WIDTH, HEIGHT))
        im = im.resize((WIDTH, HEIGHT), Image.LANCZOS)

    px = im.load()
    words = []
    for y in range(HEIGHT):
        for x in range(WIDTH):
            c = to_rgb565(*px[x, y])
            if swap:
                c = ((c & 0xFF) << 8) | (c >> 8)
            words.append(c)

    out = os.path.normpath(OUT)
    with open(out, "w") as f:
        f.write("// Generated by tools/png_to_h.py from %s\n" % os.path.basename(src))
        f.write("// Do not edit by hand. Regenerate instead.\n")
        f.write("//\n")
        f.write("// Plain RGB565 words, %d x %d, %d bytes in flash.\n"
                % (WIDTH, HEIGHT, WIDTH * HEIGHT * 2))
        f.write("// Byte order: %s. Sprites store colour byte-swapped\n"
                % ("swapped, sprite-native" if swap else "plain RGB565"))
        f.write("// (TFT_eSprite::drawPixel), and the ILI9488 path writes through\n")
        f.write("// tft_Write_16S() when swapBytes is false, so swapped is correct here.\n\n")
        f.write("#pragma once\n\n")
        f.write("#include <stdint.h>\n\n")
        f.write("#define BG_IMAGE_W  %d\n" % WIDTH)
        f.write("#define BG_IMAGE_H  %d\n\n" % HEIGHT)
        f.write("const uint16_t BG_IMAGE[%d] PROGMEM = {\n" % (WIDTH * HEIGHT))
        for i in range(0, len(words), 12):
            f.write("  " + ", ".join("0x%04X" % w for w in words[i:i + 12]) + ",\n")
        f.write("};\n")

    print("wrote %s (%d px, %d bytes of image data)"
          % (out, len(words), len(words) * 2))


if __name__ == "__main__":
    main()
